name: multiAffinity
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - bioconductor-annotate=1.70.0
  - bioconductor-annotationdbi=1.54.0
  - bioconductor-biobase=2.52.0
  - bioconductor-biocfilecache=2.0.0
  - bioconductor-biocgenerics=0.38.0
  - bioconductor-biocparallel=1.26.0
  - bioconductor-biostrings=2.60.0
  - bioconductor-delayedarray=0.18.0
  - bioconductor-deseq2=1.32.0
  - bioconductor-genefilter=1.74.0
  - bioconductor-geneplotter=1.70.0
  - bioconductor-genomeinfodb=1.28.0
  - bioconductor-genomeinfodbdata=1.2.6
  - bioconductor-genomicranges=1.44.0
  - bioconductor-ihw=1.20.0
  - bioconductor-iranges=2.26.0
  - bioconductor-keggrest=1.32.0
  - bioconductor-lpsymphony=1.20.0
  - bioconductor-matrixgenerics=1.4.0
  - bioconductor-s4vectors=0.30.0
  - bioconductor-singlecellexperiment=1.14.1
  - bioconductor-summarizedexperiment=1.22.0
  - bioconductor-waddr=1.6.1
  - bioconductor-xvector=0.32.0
  - bioconductor-zlibbioc=1.38.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.10.26
  - cairo=1.16.0
  - certifi=2021.10.8
  - curl=7.78.0
  - debugpy=1.4.1
  - decorator=5.0.9
  - entrypoints=0.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=9.4.0
  - gcc_linux-64=9.4.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=9.4.0
  - gfortran_linux-64=9.4.0
  - graphite2=1.3.13
  - gsl=2.7
  - gxx_impl_linux-64=9.4.0
  - gxx_linux-64=9.4.0
  - harfbuzz=2.9.0
  - icu=68.1
  - ipykernel=6.3.1
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.0
  - joblib=1.1.0
  - jpeg=9d
  - jupyter_client=7.0.2
  - jupyter_core=4.7.1
  - kernel-headers_linux-64=2.6.32
  - krb5=1.19.2
  - ld_impl_linux-64=2.36.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.78.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-devel_linux-64=9.4.0
  - libgcc-ng=11.1.0
  - libgfortran-ng=11.1.0
  - libgfortran5=11.1.0
  - libglib=2.68.4
  - libgomp=11.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libsanitizer=9.4.0
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=9.4.0
  - libstdcxx-ng=11.1.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - make=4.3
  - matplotlib-inline=0.1.2
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - openssl=1.1.1l
  - pandoc=2.14.2
  - pango=1.48.9
  - parso=0.8.2
  - pcre=8.45
  - pcre2=10.37
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - pixman=0.40.0
  - prompt-toolkit=3.0.20
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pygments=2.10.0
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=22.2.1
  - r=4.1
  - r-abind=1.4_5
  - r-acepack=1.4.1
  - r-arm=1.11_2
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.2.1
  - r-base=4.1.1
  - r-base64enc=0.1_3
  - r-bh=1.75.0_0
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.2
  - r-boot=1.3_28
  - r-brio=1.1.2
  - r-broom=0.7.9
  - r-cachem=1.0.6
  - r-callr=3.7.0
  - r-cellranger=1.1.0
  - r-checkmate=2.0.0
  - r-class=7.3_19
  - r-cli=3.0.1
  - r-clipr=0.7.1
  - r-cluster=2.1.2
  - r-coda=0.19_4
  - r-codetools=0.2_18
  - r-colorspace=2.0_2
  - r-cpp11=0.3.1
  - r-crayon=1.4.1
  - r-curl=4.3.2
  - r-data.table=1.14.0
  - r-dbi=1.1.1
  - r-dbplyr=2.1.1
  - r-desc=1.3.0
  - r-diffobj=0.3.4
  - r-digest=0.6.27
  - r-dplyr=1.0.7
  - r-dtplyr=1.1.0
  - r-ellipsis=0.3.2
  - r-envstats=2.4.0
  - r-eva=0.2.6
  - r-evaluate=0.14
  - r-fansi=0.4.2
  - r-farver=2.1.0
  - r-fastmap=1.1.0
  - r-fdrtool=1.2.16
  - r-filelock=1.0.2
  - r-forcats=0.5.1
  - r-foreign=0.8_81
  - r-formatr=1.11
  - r-formula=1.2_4
  - r-fs=1.5.0
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-gargle=1.2.0
  - r-generics=0.1.0
  - r-ggplot2=3.3.5
  - r-glue=1.4.2
  - r-googledrive=2.0.0
  - r-googlesheets4=0.3.0
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-haven=2.4.3
  - r-highr=0.9
  - r-hmisc=4.5_0
  - r-hms=1.1.0
  - r-htmltable=2.2.1
  - r-htmltools=0.5.2
  - r-htmlwidgets=1.5.4
  - r-httr=1.4.2
  - r-ids=1.0.1
  - r-isoband=0.2.5
  - r-jpeg=0.1_8.1
  - r-jsonlite=1.7.2
  - r-kernsmooth=2.23_20
  - r-knitr=1.34
  - r-labeling=0.4.2
  - r-lambda.r=1.2.4
  - r-lattice=0.20_44
  - r-latticeextra=0.6_29
  - r-lifecycle=1.0.0
  - r-lme4=1.1_27.1
  - r-locfit=1.5_9.4
  - r-lubridate=1.7.10
  - r-magrittr=2.0.1
  - r-markdown=1.1
  - r-mass=7.3_54
  - r-matrix=1.3_4
  - r-matrixstats=0.60.1
  - r-memoise=2.0.0
  - r-mgcv=1.8_36
  - r-mime=0.11
  - r-minqa=1.2.4
  - r-modelr=0.1.8
  - r-munsell=0.5.0
  - r-nlme=3.1_152
  - r-nloptr=1.2.2.2
  - r-nnet=7.3_16
  - r-nortest=1.0_4
  - r-openssl=1.4.5
  - r-pillar=1.6.2
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.1
  - r-plogr=0.2.0
  - r-plyr=1.8.6
  - r-png=0.1_7
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.5.2
  - r-progress=1.2.2
  - r-ps=1.6.0
  - r-purrr=0.3.4
  - r-r6=2.5.1
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.7
  - r-rcpparmadillo=0.10.6.0.0
  - r-rcppeigen=0.3.3.9.1
  - r-rcurl=1.98_1.4
  - r-readr=2.0.1
  - r-readxl=1.3.1
  - r-recommended=4.1
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-reprex=2.0.1
  - r-reshape2=1.4.4
  - r-rlang=0.4.11
  - r-rmarkdown=2.10
  - r-robustrankaggreg=1.1
  - r-rpart=4.1_15
  - r-rprojroot=2.0.2
  - r-rsqlite=2.2.5
  - r-rstudioapi=0.13
  - r-rvest=1.0.1
  - r-scales=1.1.1
  - r-selectr=0.4_2
  - r-slam=0.1_48
  - r-snow=0.4_3
  - r-spatial=7.3_14
  - r-statmod=1.4.36
  - r-stringi=1.7.4
  - r-stringr=1.4.0
  - r-survival=3.2_13
  - r-sys=3.4
  - r-testthat=3.0.4
  - r-tibble=3.1.4
  - r-tidyr=1.1.3
  - r-tidyselect=1.1.1
  - r-tidyverse=1.3.1
  - r-tinytex=0.33
  - r-tzdb=0.1.2
  - r-utf8=1.2.2
  - r-uuid=0.1_4
  - r-vctrs=0.3.8
  - r-viridis=0.6.1
  - r-viridislite=0.4.0
  - r-vroom=1.5.4
  - r-waldo=0.3.0
  - r-withr=2.4.2
  - r-xfun=0.25
  - r-xml=3.99_0.7
  - r-xml2=1.3.2
  - r-xtable=1.8_4
  - r-yaml=2.2.1
  - readline=8.1
  - sed=4.8
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - sysroot_linux-64=2.12
  - tk=8.6.11
  - tktable=2.10
  - tornado=6.1
  - traitlets=5.1.0
  - tzdata=2021a
  - wcwidth=0.2.5
  - wheel=0.37.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - cycler==0.10.0
    - kiwisolver==1.3.2
    - matplotlib==3.3.3
    - multixrank==0.0.8
    - networkx==2.6.2
    - numpy==1.19.5
    - pandas==1.2.0
    - pillow==8.3.2
    - psutil==5.8.0
    - pyparsing==2.4.7
    - pytz==2021.1
    - pyyaml==5.4.1
    - scipy==1.6.0
    - seaborn==0.11.1
